### ISSUE TITLE
Kim's lessons

### ISSUE THREAD

**Issue by maglet** [uw-madison-comps/R-plant-lesson#54]
- [ ] Add questions and keypoints to header
- [ ] Fix errors in the code later in the lesson

I'm not familiar enough with these functions to be of help here.

**Comment by kimokeefe** [comment]
Hm, I'm not entirely sure why those errors are showing up. I didn't have the code actually download the arm and mumin packages because they were already downloaded on my computer - maybe that's the issue? 

I changed that, added questions / key points, and changed the first figures / regression in an updated version of the .rmd file. However, I tried uploading the new version using the code that you suggested in another issue, but it still won't work for me (it won't even create an html file or md file on my computer). Can I email you the new version? I'm sorry!

**Comment by maglet** [comment]
I set the code blocks that had errors to not evaluate, and i think things are working now
