### ISSUE TITLE
Scientific intro plot and teaser

### ISSUE THREAD

**Issue by SteveGoldstein** [uw-madison-comps/R-plant-lesson#59]
Suggestion for intro to the data section of lesson 02:  

- Use this image from the ggforitfy package vignette:  https://cran.r-project.org/web/packages/ggfortify/vignettes/plot_pca.html
![image](https://user-images.githubusercontent.com/7879996/64456772-a9a07000-d0b6-11e9-80ea-ac0fa7fc28d1.png)

- As the final challenge in the ggplot lesson (or a homework challenge):  Have the learners install ggfortify and work through the vignette, reproducing this plot. 

- Don't introduce the plant phys data in the intro to data section of lesson 02;  leave that to Kim in on the last day.   From a brief discussion I had with Kim yesterday, it seems like we can't really do justice to those data by whipping up a quick plot and explaining it in a short paragraph.

What do you think:  @maglet @kathrynmichel @kimokeefe

**Comment by kimokeefe** [comment]
Well I imagine you'll have to give a general introduction to the plant phys dataset on either the first or second day because you are using it in the dplyr and ggplot lessons, correct?

And yes, there's not really a single "take-home message" plot that I could produce since the results are fairly subtle and involve a lot of interactions. You could take a look at my paper to see if any of those figures fit what you were thinking, but I don't think any one of those individually tell the story - they sort of work together to tell the story.

I could still write up a short summary paragraph for you if you like? Just let me know.

**Comment by SteveGoldstein** [comment]
Let's split this issue into intro to iris and and intro to phys_data.
      The intro to the phys_data is discussed in #67 so we don't need to discuss it here.

**Comment by SteveGoldstein** [comment]
The PC plot was voted down at Monday's meeting because we can't assume the learners know about PCA.  Kathryn will come up with some other plot that points toward clustering of species.

**Comment by kathrynmichel** [comment]
Can someone incorporate this plot right after the image of the irises? I think it will suffice for differentiating the three groups, and is still simple.

ggplot(data = iris, 
       mapping = aes(x = Petal.Width, 
                     y = Petal.Length))+
  geom_point(aes(color = Species))+
  ggtitle("Iris Petal Length vs Width")

**Comment by SteveGoldstein** [comment]
Yes, I'll do incorporate it (later today).
